spring:
  application:
    name: realtime
  web:
    cors:
      allowed-origins:
        - http://localhost:5173
        - http://localhost:3000 # React 개발 서버 주소
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

server:
  port: 8080

weather:
  api:
    key: ${WEATHER_API_KEY}
