spring:
  application:
    name: realtime
  web:
    cors:
      allowed-origins:
        - http://localhost:5173
        - http://localhost:3000
        - http://localhost:3001 # React 개발 서버 주소
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  websocket:
    allowed-origins: "*"    # 웹소켓 CORS 설정 추가

server:
  port: 8080

weather:
  api:
    key: ${WEATHER_API_KEY}

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.yth.realtime: DEBUG
    com.influxdb.client: DEBUG
    com.yth.realtime.service: DEBUG
    com.yth.realtime.controller: DEBUG
    com.ghgande.j2mod: DEBUG
    org.springframework.web.socket: TRACE    # 웹소켓 로그 레벨을 TRACE로 변경

influxdb:
  url: http://localhost:8086
  token: zZpdEV4H9H4iNYjc4FjIdntwA2FdmSxAfP6URmsNNJKPpVTiyzgNxqkLL33ZJYpuZXMIJVKLnMVM9Nmq-TlrCA==
  org: youn
  bucket: ydata
